using CsvAiQueryDemo.Models;
using System.Text;
using System.Text.Json;

namespace CsvAiQueryDemo.Services;

public sealed class QueryIntentService
{
    private readonly HttpClient _httpClient;
    private readonly string _systemPrompt;
    private readonly OpenAiProviderOptions _providerOptions;
    private readonly bool _fallbackEnabled;

    public QueryIntentService(HttpClient httpClient, string promptPath)
    {
        _httpClient = httpClient;
        _systemPrompt = File.ReadAllText(promptPath);
        _providerOptions = OpenAiProviderOptions.FromEnvironment();
        _fallbackEnabled = string.Equals(
            Environment.GetEnvironmentVariable("OPENAI_ENABLE_FALLBACK"),
            "true",
            StringComparison.OrdinalIgnoreCase);
    }

    public async Task<QueryIntentGeneration> CreateIntentAsync(
        string userQuestion,
        DatasetProfile datasetProfile,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(_providerOptions.ApiKey))
        {
            if (_fallbackEnabled)
            {
                return CreateFallbackGeneration(
                    userQuestion,
                    "LLM API key is not configured");
            }

            throw new InvalidOperationException("LLM API key is not configured. Set OPENAI_API_KEY, AZURE_OPENAI_API_KEY or AI_API_KEY in .env, or enable OPENAI_ENABLE_FALLBACK=true for demo fallback mode.");
        }

        if (_providerOptions.Provider == OpenAiProvider.AzureChatCompletions
            && string.IsNullOrWhiteSpace(_providerOptions.RequestUri))
        {
            throw new InvalidOperationException("Azure OpenAI endpoint is not configured. Set AZURE_OPENAI_ENDPOINT in .env.");
        }

        var payload = BuildRequestPayload(userQuestion, datasetProfile);
        using var request = new HttpRequestMessage(HttpMethod.Post, _providerOptions.RequestUri);
        _providerOptions.ApplyAuthentication(request);
        request.Content = new StringContent(payload, Encoding.UTF8, "application/json");

        try
        {
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                if (!_fallbackEnabled)
                {
                    throw new InvalidOperationException($"LLM query intent request failed: {(int)response.StatusCode} {response.ReasonPhrase}. Endpoint: {_providerOptions.RequestUri}");
                }

                return CreateFallbackGeneration(
                    userQuestion,
                    $"LLM query intent request failed: {(int)response.StatusCode} {response.ReasonPhrase}");
            }

            var outputText = ExtractOutputText(responseBody);
            var usage = ExtractUsage(responseBody);
            var intent = JsonSerializer.Deserialize<QueryIntent>(outputText, JsonOptions())
                ?? throw new InvalidOperationException("OpenAI returned an empty QueryIntent.");

            return new QueryIntentGeneration(intent, UsedFallback: false, Message: "QueryIntent generated by LLM.", usage);
        }
        catch (HttpRequestException ex)
        {
            if (!_fallbackEnabled)
            {
                throw new InvalidOperationException($"LLM connection failed for endpoint {_providerOptions.RequestUri}: {ex.Message}", ex);
            }

            return CreateFallbackGeneration(userQuestion, $"LLM connection failed: {ex.Message}");
        }
        catch (TaskCanceledException ex)
        {
            if (!_fallbackEnabled)
            {
                throw new InvalidOperationException($"LLM request timed out for endpoint {_providerOptions.RequestUri}: {ex.Message}", ex);
            }

            return CreateFallbackGeneration(userQuestion, $"LLM request timed out: {ex.Message}");
        }
    }

    public string BuildUserPrompt(string userQuestion, DatasetProfile datasetProfile)
    {
        var profileJson = JsonSerializer.Serialize(datasetProfile, JsonOptions());
        var schemaJson = JsonSerializer.Serialize(QueryIntentSchema, JsonOptions());

        return $"""
DatasetProfile JSON:
{profileJson}

User question:
{userQuestion}

Allowed QueryIntent schema:
{schemaJson}
""";
    }

    public string BuildRequestPayload(string userQuestion, DatasetProfile datasetProfile)
    {
        var userPrompt = BuildUserPrompt(userQuestion, datasetProfile);
        if (_providerOptions.Provider == OpenAiProvider.AzureChatCompletions)
        {
            var azurePayload = new
            {
                messages = new object[]
                {
                    new { role = "system", content = _systemPrompt },
                    new { role = "user", content = userPrompt }
                },
                max_completion_tokens = 16384,
                response_format = new
                {
                    type = "json_schema",
                    json_schema = new
                    {
                        name = "query_intent",
                        schema = QueryIntentSchema,
                        strict = false
                    }
                }
            };

            return JsonSerializer.Serialize(azurePayload, JsonOptions());
        }

        var payload = new
        {
            model = _providerOptions.ModelOrDeployment,
            input = new object[]
            {
                new
                {
                    role = "system",
                    content = new object[] { new { type = "input_text", text = _systemPrompt } }
                },
                new
                {
                    role = "user",
                    content = new object[] { new { type = "input_text", text = userPrompt } }
                }
            },
            text = new
            {
                format = new
                {
                    type = "json_schema",
                    name = "query_intent",
                    schema = QueryIntentSchema,
                    strict = false
                }
            }
        };

        return JsonSerializer.Serialize(payload, JsonOptions());
    }

    public ModelPromptInfo BuildPromptInfo(string userQuestion, DatasetProfile datasetProfile)
    {
        var provider = _providerOptions.Provider == OpenAiProvider.AzureChatCompletions
            ? "Azure OpenAI Chat Completions"
            : "OpenAI Responses API";

        return new ModelPromptInfo(
            provider,
            _systemPrompt,
            BuildUserPrompt(userQuestion, datasetProfile),
            BuildRequestPayload(userQuestion, datasetProfile));
    }

    public static void SaveIntent(QueryIntent intent, string filePath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(filePath) ?? ".");
        File.WriteAllText(filePath, JsonSerializer.Serialize(intent, JsonOptions()));
    }

    private static QueryIntent CreateFallbackIntent(string userQuestion)
    {
        var normalized = userQuestion.ToLowerInvariant();

        if (normalized.Contains("unterschiedliche") && normalized.Contains("vornamen"))
        {
            return new QueryIntent { Operation = "distinct", Column = "Vorname" };
        }

        if (normalized.Contains("häufig") && normalized.Contains("vornamen"))
        {
            return new QueryIntent { Operation = "top_values", Column = "Vorname", Limit = 5 };
        }

        if (normalized.Contains("nachname") && normalized.Contains("müller"))
        {
            return new QueryIntent { Operation = "filter", Column = "Nachname", Operator = "equals", Value = "Müller", Limit = 50 };
        }

        if (normalized.Contains("mail") && normalized.Contains("example.com"))
        {
            return new QueryIntent { Operation = "count", Column = "Mail", Operator = "contains", Value = "example.com" };
        }

        if (normalized.Contains("vorname") && normalized.Contains("max"))
        {
            return new QueryIntent { Operation = "count", Column = "Vorname", Operator = "equals", Value = "Max" };
        }

        return new QueryIntent { Operation = "count" };
    }

    private static QueryIntentGeneration CreateFallbackGeneration(string userQuestion, string reason)
    {
        return new QueryIntentGeneration(
            CreateFallbackIntent(userQuestion),
            UsedFallback: true,
            Message: $"{reason}. Used a local demo fallback for supported example questions.",
            TokenUsage.Zero);
    }

    private static string ExtractOutputText(string responseBody)
    {
        using var document = JsonDocument.Parse(responseBody);
        if (document.RootElement.TryGetProperty("output_text", out var outputText))
        {
            return outputText.GetString() ?? string.Empty;
        }

        if (document.RootElement.TryGetProperty("output", out var outputItems))
        {
            foreach (var outputItem in outputItems.EnumerateArray())
            {
                if (!outputItem.TryGetProperty("content", out var contentItems))
                {
                    continue;
                }

                foreach (var contentItem in contentItems.EnumerateArray())
                {
                    if (contentItem.TryGetProperty("text", out var text))
                    {
                        return text.GetString() ?? string.Empty;
                    }
                }
            }
        }

        if (document.RootElement.TryGetProperty("choices", out var choices))
        {
            foreach (var choice in choices.EnumerateArray())
            {
                if (choice.TryGetProperty("message", out var message)
                    && message.TryGetProperty("content", out var content))
                {
                    return content.GetString() ?? string.Empty;
                }
            }
        }

        throw new InvalidOperationException("LLM response did not contain text output.");
    }

    private static TokenUsage ExtractUsage(string responseBody)
    {
        using var document = JsonDocument.Parse(responseBody);
        if (!document.RootElement.TryGetProperty("usage", out var usage))
        {
            return TokenUsage.Zero;
        }

        var inputTokens = GetIntProperty(usage, "input_tokens")
            ?? GetIntProperty(usage, "prompt_tokens")
            ?? 0;
        var outputTokens = GetIntProperty(usage, "output_tokens")
            ?? GetIntProperty(usage, "completion_tokens")
            ?? 0;
        var totalTokens = GetIntProperty(usage, "total_tokens") ?? inputTokens + outputTokens;

        return new TokenUsage(inputTokens, outputTokens, totalTokens);
    }

    private static int? GetIntProperty(JsonElement element, string propertyName)
    {
        if (element.TryGetProperty(propertyName, out var value) && value.TryGetInt32(out var result))
        {
            return result;
        }

        return null;
    }

    private static JsonSerializerOptions JsonOptions()
    {
        return new JsonSerializerOptions { WriteIndented = true, PropertyNameCaseInsensitive = true };
    }

    private static readonly object QueryIntentSchema = new
    {
        type = "object",
        additionalProperties = false,
        properties = new
        {
            Operation = new { type = "string", @enum = new[] { "count", "filter", "distinct", "top_values", "group_by_count" } },
            Column = new { type = new[] { "string", "null" } },
            Operator = new { type = new[] { "string", "null" }, @enum = new object?[] { "equals", "contains", "starts_with", "ends_with", null } },
            Value = new { type = new[] { "string", "null" } },
            GroupBy = new { type = new[] { "string", "null" } },
            Limit = new { type = new[] { "integer", "null" } }
        },
        required = new[] { "Operation" }
    };
}
