using CsvAiQueryDemo.Models;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace CsvAiQueryDemo.Services;

public sealed class QueryIntentService
{
    private const string DefaultModel = "gpt-5.2";
    private readonly HttpClient _httpClient;
    private readonly string _systemPrompt;
    private readonly string? _apiKey;
    private readonly string _model;

    public QueryIntentService(HttpClient httpClient, string promptPath)
    {
        _httpClient = httpClient;
        _systemPrompt = File.ReadAllText(promptPath);
        _apiKey = Environment.GetEnvironmentVariable("OPENAI_API_KEY");
        _model = Environment.GetEnvironmentVariable("OPENAI_MODEL") ?? DefaultModel;
    }

    public async Task<QueryIntentGeneration> CreateIntentAsync(
        string userQuestion,
        DatasetProfile datasetProfile,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(_apiKey))
        {
            return new QueryIntentGeneration(
                CreateFallbackIntent(userQuestion),
                UsedFallback: true,
                Message: "OpenAI API key is not configured. Used a local demo fallback for supported example questions.");
        }

        var payload = BuildRequestPayload(userQuestion, datasetProfile);
        using var request = new HttpRequestMessage(HttpMethod.Post, "https://api.openai.com/v1/responses");
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", _apiKey);
        request.Content = new StringContent(payload, Encoding.UTF8, "application/json");

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        var responseBody = await response.Content.ReadAsStringAsync(cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            throw new InvalidOperationException($"OpenAI query intent request failed: {(int)response.StatusCode} {response.ReasonPhrase}");
        }

        var outputText = ExtractOutputText(responseBody);
        var intent = JsonSerializer.Deserialize<QueryIntent>(outputText, JsonOptions())
            ?? throw new InvalidOperationException("OpenAI returned an empty QueryIntent.");

        return new QueryIntentGeneration(intent, UsedFallback: false, Message: "QueryIntent generated by OpenAI.");
    }

    public string BuildUserPrompt(string userQuestion, DatasetProfile datasetProfile)
    {
        var profileJson = JsonSerializer.Serialize(datasetProfile, JsonOptions());
        var schemaJson = JsonSerializer.Serialize(QueryIntentSchema, JsonOptions());

        return $"""
DatasetProfile JSON:
{profileJson}

User question:
{userQuestion}

Allowed QueryIntent schema:
{schemaJson}
""";
    }

    public string BuildRequestPayload(string userQuestion, DatasetProfile datasetProfile)
    {
        var userPrompt = BuildUserPrompt(userQuestion, datasetProfile);
        var payload = new
        {
            model = _model,
            input = new object[]
            {
                new
                {
                    role = "system",
                    content = new object[] { new { type = "input_text", text = _systemPrompt } }
                },
                new
                {
                    role = "user",
                    content = new object[] { new { type = "input_text", text = userPrompt } }
                }
            },
            text = new
            {
                format = new
                {
                    type = "json_schema",
                    name = "query_intent",
                    schema = QueryIntentSchema,
                    strict = false
                }
            }
        };

        return JsonSerializer.Serialize(payload, JsonOptions());
    }

    public static void SaveIntent(QueryIntent intent, string filePath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(filePath) ?? ".");
        File.WriteAllText(filePath, JsonSerializer.Serialize(intent, JsonOptions()));
    }

    private static QueryIntent CreateFallbackIntent(string userQuestion)
    {
        var normalized = userQuestion.ToLowerInvariant();

        if (normalized.Contains("unterschiedliche") && normalized.Contains("vornamen"))
        {
            return new QueryIntent { Operation = "distinct", Column = "Vorname" };
        }

        if (normalized.Contains("häufig") && normalized.Contains("vornamen"))
        {
            return new QueryIntent { Operation = "top_values", Column = "Vorname", Limit = 5 };
        }

        if (normalized.Contains("nachname") && normalized.Contains("müller"))
        {
            return new QueryIntent { Operation = "filter", Column = "Nachname", Operator = "equals", Value = "Müller", Limit = 50 };
        }

        if (normalized.Contains("mail") && normalized.Contains("example.com"))
        {
            return new QueryIntent { Operation = "count", Column = "Mail", Operator = "contains", Value = "example.com" };
        }

        if (normalized.Contains("vorname") && normalized.Contains("max"))
        {
            return new QueryIntent { Operation = "count", Column = "Vorname", Operator = "equals", Value = "Max" };
        }

        return new QueryIntent { Operation = "count" };
    }

    private static string ExtractOutputText(string responseBody)
    {
        using var document = JsonDocument.Parse(responseBody);
        if (document.RootElement.TryGetProperty("output_text", out var outputText))
        {
            return outputText.GetString() ?? string.Empty;
        }

        if (document.RootElement.TryGetProperty("output", out var outputItems))
        {
            foreach (var outputItem in outputItems.EnumerateArray())
            {
                if (!outputItem.TryGetProperty("content", out var contentItems))
                {
                    continue;
                }

                foreach (var contentItem in contentItems.EnumerateArray())
                {
                    if (contentItem.TryGetProperty("text", out var text))
                    {
                        return text.GetString() ?? string.Empty;
                    }
                }
            }
        }

        throw new InvalidOperationException("OpenAI response did not contain text output.");
    }

    private static JsonSerializerOptions JsonOptions()
    {
        return new JsonSerializerOptions { WriteIndented = true, PropertyNameCaseInsensitive = true };
    }

    private static readonly object QueryIntentSchema = new
    {
        type = "object",
        additionalProperties = false,
        properties = new
        {
            Operation = new { type = "string", @enum = new[] { "count", "filter", "distinct", "top_values", "group_by_count" } },
            Column = new { type = new[] { "string", "null" } },
            Operator = new { type = new[] { "string", "null" }, @enum = new object?[] { "equals", "contains", "starts_with", "ends_with", null } },
            Value = new { type = new[] { "string", "null" } },
            GroupBy = new { type = new[] { "string", "null" } },
            Limit = new { type = new[] { "integer", "null" } }
        },
        required = new[] { "Operation" }
    };
}
